# Service.yaml file for exposing tomcat application
apiVersion: v1

kind: Service

metadata:

  name: hello-service

spec:

  type: NodePort

  selector:

    app: hello

  ports:

  - protocol: TCP

    port: 8080

    targetPort: 8080
